name: 'AI CodeMentor'
description: 'AI-powered code review for Pull Requests'
author: 'AI CodeMentor'
inputs:
  openai_api_key:
    description: 'OpenAI API key'
    required: true
  slack_bot_token:
    description: 'Slack Bot Token for notifications'
    required: false
  slack_channel:
    description: 'Slack channel to send notifications'
    required: false
    default: '#code-reviews'
  discord_webhook_url:
    description: 'Discord Webhook URL for notifications'
    required: false
  model:
    description: 'OpenAI model to use (default: gpt-4)'
    required: false
    default: 'gpt-4'
  skip_labels:
    description: 'Labels to skip review (comma-separated)'
    required: false
    default: 'no-ai-review,skip-review'
  exclude_patterns:
    description: 'Patterns to exclude from review (comma-separated)'
    required: false
    default: 'docs/*.md,.github/*,requirements.txt,README.md'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install openai PyGithub python-dotenv flake8 slack-sdk discord-webhook

    - name: Run AI Review
      shell: bash
      run: python ${{ github.action_path }}/scripts/review.py
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
        SLACK_CHANNEL: ${{ inputs.slack_channel }}
        DISCORD_WEBHOOK_URL: ${{ inputs.discord_webhook_url }}
        AI_MODEL: ${{ inputs.model }}
        SKIP_LABELS: ${{ inputs.skip_labels }}
        EXCLUDE_PATTERNS: ${{ inputs.exclude_patterns }} 