########################################################################################
# AI CodeMentor 자동 코드 리뷰 워크플로우
# 이 워크플로우는 PR이 생성되거나 업데이트될 때 자동으로 AI 코드 리뷰를 실행합니다.
########################################################################################

name: AI CodeMentor Review

# 워크플로우 트리거 설정
# opened: PR이 새로 생성될 때
# synchronize: PR에 새로운 커밋이 추가될 때
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    # 실행 환경 설정 (Ubuntu 최신 버전)
    runs-on: ubuntu-latest
    
    # 권한 설정
    # pull-requests: write - PR에 코멘트를 작성하기 위해 필요
    # contents: read - 코드 내용을 읽기 위해 필요
    permissions:
      pull-requests: write
      contents: read

    steps:
      # 1. 코드 체크아웃
      # fetch-depth: 0 - 모든 커밋 히스토리를 가져와 diff 생성에 활용
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Python 설정
      # Python 3.10 버전 설치
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. 필요한 라이브러리 설치
      # requirements.txt 파일에 정의된 종속성 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. AI 코드 리뷰 실행
      # 다음 환경 변수를 설정할 수 있습니다:
      # - OPENAI_API_KEY: (필수) OpenAI API 키
      # - GITHUB_TOKEN: (필수) GitHub 토큰, 자동으로 제공됨
      # - SLACK_WEBHOOK_URL: (선택) Slack 알림용 웹훅 URL
      # - DISCORD_WEBHOOK_URL: (선택) Discord 알림용 웹훅 URL
      # - LANGUAGE: (선택) 리뷰 언어, 'ko' 또는 'en' (기본값: 'en')
      # - REVIEW_TYPE: (선택) 리뷰 유형, 'standard', 'concise', 'detailed' (기본값: 'standard')
      # - MAX_FILES: (선택) 리뷰할 최대 파일 수 (기본값: 5)
      # - MAX_FILE_SIZE: (선택) 리뷰할 최대 파일 크기 (KB) (기본값: 500)
      # - EXCLUDE_PATTERNS: (선택) 리뷰에서 제외할 파일 패턴 (예: '*.md,docs/*')
      # - INCLUDE_PATTERNS: (선택) 리뷰에 포함할 파일 패턴 (예: 'src/*.js')
      # - SKIP_LABELS: (선택) 리뷰를 건너뛸 PR 라벨 (예: 'no-ai-review,skip-review')
      # - MODEL: (선택) 사용할 OpenAI 모델 (기본값: 'gpt-4')
      # - SLACK_CHANNEL: (선택) Slack 알림을 보낼 채널 (기본값: '#code-reviews')
      - name: Run AI Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/review.py 